#!/usr/bin/env python3
"""Generate all PlantUML + boxes example diagrams for documentation.

PlantUML text/HTML outputs are generated by sysmlpy's view functions;
PNGs are rendered with a local plantuml.jar (PLANTUML_JAR env var or
~/tools/plantuml.jar). boxes views render natively to braille text and
SVG — no Java required.

Regenerated for v0.68.0 (repaired notation: official edge encodings,
nested composite states, boxes-backed iv/afv, opt-in legends).
"""

import sysmlpy
from sysmlpy.plantuml import (
    as_graphical_rendering, as_general_view, as_package_view,
    as_action_flow_view, as_interconnection_view, as_state_transition_view,
    as_tree_diagram, as_element_table, as_textual_notation,
    as_tabular_view, as_data_value_tabular_view, as_relationship_matrix_view,
)
from sysmlpy.boxes_view import (
    render_state_transition_view,
    render_interconnection_view_boxes,
    render_action_flow_view_boxes,
    as_state_transition_view_boxes,
    as_interconnection_view_boxes,
    as_action_flow_view_boxes,
)
import subprocess
import os

OUTPUT_DIR = "docs/plantuml-examples"
PLANTUML_JAR = os.environ.get(
    "PLANTUML_JAR", os.path.expanduser("~/tools/plantuml.jar"))
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Sample model for most examples
VEHICLE_MODEL = sysmlpy.loads("""
package Vehicle {
    part def Wheel {
        attribute radius : Real;
        attribute pressure : Real;
    }
    part def BrakeSystem {
        attribute padThickness : Real;
    }
    part def VehicleAssembly {
        part frontLeft : Wheel;
        part frontRight : Wheel;
        part brakes : BrakeSystem;
    }
    part myVehicle : VehicleAssembly;
}
""")


def generate_puml(name, puml_text):
    """Save PlantUML text and render to PNG."""
    puml_path = os.path.join(OUTPUT_DIR, f"{name}.puml")
    png_path = os.path.join(OUTPUT_DIR, f"{name}.png")

    with open(puml_path, 'w') as f:
        f.write(puml_text)

    if not os.path.exists(PLANTUML_JAR):
        print(f"⚠ PlantUML JAR not found ({PLANTUML_JAR}), saved {name}.puml only")
        return

    try:
        subprocess.run(
            ['java', '-jar', PLANTUML_JAR, '-tpng', f"{name}.puml"],
            cwd=OUTPUT_DIR,
            check=True,
            capture_output=True
        )
        print(f"✓ Generated {name}.puml + .png")
    except subprocess.CalledProcessError as e:
        print(f"✗ Failed to render {name}: {e.stderr.decode()}")


def generate_boxes(name, braille_text, svg_text=None):
    """Save a boxes view as braille text (+ optional SVG)."""
    txt_path = os.path.join(OUTPUT_DIR, f"{name}.txt")
    with open(txt_path, 'w') as f:
        f.write(braille_text)
    print(f"✓ Generated {name}.txt")
    if svg_text is not None:
        svg_path = os.path.join(OUTPUT_DIR, f"{name}.svg")
        with open(svg_path, 'w') as f:
            f.write(svg_text)
        print(f"✓ Generated {name}.svg")


def generate_md(name, md_text):
    md_path = os.path.join(OUTPUT_DIR, f"{name}.md")
    with open(md_path, 'w') as f:
        f.write(md_text)
    print(f"✓ Generated {name}.md")


print("=" * 60)
print("Generating Diagram Examples (v0.68.0)")
print("=" * 60)

# 1. Usage vs Definition
print("\n1. Usage vs Definition")
model1 = sysmlpy.loads("""
package Example {
    part def Engine;
    part myEngine : Engine;
}
""")
generate_puml("01-usage-vs-definition", as_graphical_rendering(model1))

# 2. Relationship Arrows
print("\n2. Relationship Arrows")
model2 = sysmlpy.loads("""
package Example {
    part def Base;
    part def Derived :> Base;
    part def Container {
        part contained : Base;
    }
}
""")
generate_puml("02-relationships", as_graphical_rendering(model2))

# 3. Vehicle Structure (B&W)
print("\n3. Vehicle Structure")
generate_puml("03-vehicle-structure", as_graphical_rendering(VEHICLE_MODEL, style="bw"))

# 4. B&W Style
print("\n4. B&W Style")
generate_puml("04-bw-style", as_general_view(VEHICLE_MODEL, style="bw"))

# 5. Interconnection
print("\n6. Interconnection")
model6 = sysmlpy.loads("""
package System {
    part def Sensor { port output; }
    part def Processor { port input; port output; }
    part def Actuator { port input; }
    part def Controller {
        part s : Sensor;
        part p : Processor;
        part a : Actuator;
        flow f1 from s.output to p.input;
        flow f2 from p.output to a.input;
    }
}
""")
generate_puml("06-interconnection", as_interconnection_view(model6))

# 7. General View
print("\n7. General View")
generate_puml("07-general-view", as_general_view(VEHICLE_MODEL))

# 8. Package View
print("\n8. Package View")
model8 = sysmlpy.loads("""
package VehicleSystem {
    package Powertrain {
        part def Engine;
        part def Transmission;
    }
    package Chassis {
        part def Wheel;
        part def Suspension;
    }
}
""")
generate_puml("08-package-view", as_package_view(model8))

# 9. Action Flow View
print("\n10. Action Flow View")
model13 = sysmlpy.loads("""
package Activity {
    action def Start;
    action def Process;
    action def End;
    part system {
        action start : Start;
        action process : Process;
        action finish : End;
        flow f1 from start to process;
        flow f2 from process to finish;
    }
}
""")
generate_puml("10-action-flow-view", as_action_flow_view(model13))

# 10. State Transition View (with real transitions)
print("\n11. State Transition View")
model14 = sysmlpy.loads("""
package States {
    state def Operational {
        state Idle;
        state Running;
        state Stopped;
        transition t1 first Idle then Running;
        transition Running then Idle;
        transition Running then Stopped;
    }
}
""")
operational = model14.find('Operational')[0]
generate_puml("11-state-transition-view",
              as_state_transition_view(model14, focus=operational))

# 11. Tree Diagram
print("\n12. Tree Diagram")
generate_puml("12-tree-diagram", as_tree_diagram(VEHICLE_MODEL))

# 12. Element Table
print("\n13. Element Table")
generate_puml("13-element-table", as_element_table(VEHICLE_MODEL))

# 13. Textual Notation
print("\n14. Textual Notation")
generate_puml("14-textual-notation", as_textual_notation(VEHICLE_MODEL))

# 14. Tabular View
print("\n15. Tabular View")
generate_md("15-tabular-view",
            as_tabular_view(VEHICLE_MODEL, output_format="markdown"))

# 15. Data Value View
print("\n16. Data Value View")
generate_md("16-data-value-view",
            as_data_value_tabular_view(VEHICLE_MODEL, output_format="markdown"))

# 16. Relationship Matrix
print("\n17. Relationship Matrix")
generate_md("17-relationship-matrix",
            as_relationship_matrix_view(VEHICLE_MODEL, output_format="markdown"))

# 17. Tabular View (Color) - HTML format for styling
print("\n18. Tabular View (Color)")
generate_md("18-tabular-view-color",
            as_tabular_view(VEHICLE_MODEL, output_format="html", style="color")
            ) if False else None
# 18 is HTML — keep the raw file name convention:
html = as_tabular_view(VEHICLE_MODEL, output_format="html", style="color")
with open(os.path.join(OUTPUT_DIR, "18-tabular-view-color.html"), 'w') as f:
    f.write(html)
print("✓ Generated 18-tabular-view-color.html")

# ------------------------------------------------------------------
# boxes views (v0.68.0) — Java-free braille + SVG, rendered natively
# ------------------------------------------------------------------

ST_MODEL = sysmlpy.loads("""
package Drive {
    state def VehicleStates {
        state off;
        state starting;
        state running {
            state idle;
            state propelling;
            state stopped;
        }
        transition t1 first off then starting;
        transition starting then running;
        transition running then stopped;
        transition stopped then off;
    }
}
""")

IV_MODEL = sysmlpy.loads("""
package Powertrain {
    part def Engine {
        port powerOut;
        attribute power : Real;
    }
    part def Drivetrain {
        port powerIn;
        attribute ratio : Real;
    }
    part def Pump { port outflow; }
    part def Tank { port intake; }
    part engine : Engine;
    part drivetrain : Drivetrain;
    part pump : Pump;
    part tank : Tank;
    connection clutch connect engine.powerOut to drivetrain.powerIn;
    connection feed connect pump to tank;
}
""")

AFV_MODEL = sysmlpy.loads("""
package EnergyFlow {
    action def Torque { in fuelCommand; out torque; }
    action def Inject { in fuelCommand; }
    part vehicle {
        action providePower : Torque;
        action injectFuel : Inject;
        action coolDown;
        flow providePower.torque to injectFuel.fuelCommand;
    }
}
""")

print("\n19. State Transition View (boxes, braille + SVG)")
st_boxes = as_state_transition_view_boxes(ST_MODEL)
generate_boxes("19-state-transition-boxes",
               st_boxes.render(), st_boxes.render_svg())

print("\n20. Interconnection View (boxes, braille + SVG)")
iv_boxes = as_interconnection_view_boxes(IV_MODEL)
generate_boxes("20-interconnection-boxes",
               iv_boxes.render(), iv_boxes.render_svg())

print("\n21. Action Flow View (boxes, braille + SVG)")
afv_boxes = as_action_flow_view_boxes(AFV_MODEL)
generate_boxes("21-action-flow-boxes",
               afv_boxes.render(), afv_boxes.render_svg())

print("\n" + "=" * 60)
print("Generation complete!")